name: Build and Publish Docker Image

on:
  push:
    tags: "**"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase repository name
        id: lowercase-repo-name
        uses: ASzc/change-string-case-action@v2
        with:
          string: "${{ github.repository }}"

      - name: Build and Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .docker/Dockerfile
          file: .docker/Dockerfile
          tags: ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
        env:
          DOCKER_BUILDKIT: 1
